#:schema file://node_modules/wrangler/config-schema.json
name = "workers-assets-test-remix"
compatibility_date = "2024-08-21"

main = "./build/worker/index.js"
experimental_assets = { directory = "./build/client" }
